site_name: MuleSoft Notes
site_description: Estudos técnicos sobre engenharia de software, arquitetura, segurança, performance, integrações e MuleSoft

docs_dir: docs
site_dir: site

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Português:
      - Visão geral: pt/index.md
      - Segurança:
          - Criptografia: pt/seguranca/criptografia.md
      - Performance: pt/performance/index.md
  - English:
      - Overview: en/index.md
      - Security:
          - Cryptography: en/security/cryptography.md
      - Performance: en/performance/index.md
